//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Categorycrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product8
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CategoryName { get; set; }
    
        public virtual Category9 Category9 { get; set; }
        public virtual Category9 Category91 { get; set; }
    }
}
